# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://meheller.github.io',
                'git_url': 'https://github.com/meheller/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.myModule': { 'nbdev_hello_world.myModule.foo': ('core.html#foo', 'nbdev_hello_world/myModule.py'),
                                            'nbdev_hello_world.myModule.say_hello': ( 'core.html#say_hello',
                                                                                      'nbdev_hello_world/myModule.py')}}}
